import Head from 'next/head';
import { Button } from '@mui/material';

export default function Home() {
  function test() {
    fetch('/api/test')
      .then((res) => res.json)
      .then((data) => console.log(data));
  }

  return (
    <>
      {/*todo : 헤드 컴포넌트로 분리하기*/}
      <Head>
        <title>Portlog | 메인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button onClick={test}>test</Button>
      </main>
    </>
  );
}
