import Head from 'next/head';

export default function Home() {
  return (
    <>
      {/*todo : 헤드 컴포넌트로 분리하기*/}
      <Head>
        <title>Portlog | 메인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
